name: Telegram ASCII Bot

on:
  schedule:
    - cron: '0 */5 * * *' 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies (Chafa)
        run: |
          sudo apt-get update
          sudo apt-get install -y chafa

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
        run: python main.py
